apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-provisioner
data:
  file.system.id: {{ efs.file.system.id }}
  aws.region: us-west-2
  provisioner.name: example.com/aws-efs
  dns.name: {fs.id}.efs.{your.region}.amazonaws.com
